### ISSUE TITLE
DGRWrapper, FPFHWrapper looks does not exist

### ISSUE THREAD

**Issue by raucha** [chrischoy/DeepGlobalRegistration#1]
hello chrischoy, Thank you for great work.

When I tried to run KITTI test script below, 
```
python -m scripts.test_kitti --kitti_dir /path/to/kitti/ --weights /path/to/dgr_kitti.pth
```

I got error like below
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Documents/MEGA/github/DeepGlobalRegistration/scripts/test_kitti.py", line 21, in <module>
    from scripts.test_3dmatch import DGRWrapper, FPFHWrapper, FCGFWrapper, rte_rre
ImportError: cannot import name 'DGRWrapper' from 'scripts.test_3dmatch' (/Documents/MEGA/github/DeepGlobalRegistration/scripts/test_3dmatch.py)
```
`DGRWrapper`,  `FPFHWrapper`, `FCGFWrapper` looks not exist in this repository.

How can i fix this test script?

By the way, `scripts.test_3dmatch` looks working fine.

**Comment by gitouni** [comment]
I don't know why this issue was closed. `FCGFWrapper` is still not defined in line 109 of test_kitti.py.
```py
if isinstance(method, FCGFWrapper):
        filename += '_' + method.method
        if 'ransac' in method.method:
```
Please fix it, thank you.
