### ISSUE TITLE
KeyError: 'feat_model'

### ISSUE THREAD

**Issue by HOUYONGKUO** [chrischoy/DeepGlobalRegistration#27]
Hi! 
Thank you for your interesting work.
When I tested the demo, I got the error about  'feat_model'. How to get this “feat_model”？
In addition, according to the current version of MinkowskiEngine, it may be possible to replace "has_bias" with "bias".
Thanks.

Best wishes.

log:
 python demo.py
=> loading checkpoint 'ResUNetBN2C-feat32-3dmatch-v0.05.pth'
=> Setting voxel size to 0.05
Traceback (most recent call last):
  File "/home/houyongkuo/Documents/DeepGlobalRegistration/core/deep_global_registration.py", line 94, in __init__
    FCGFModel = load_model(network_config['feat_model'])
KeyError: 'feat_model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 40, in <module>
    dgr = DeepGlobalRegistration(config)
  File "/home/houyongkuo/Documents/DeepGlobalRegistration/core/deep_global_registration.py", line 104, in __init__
    self.fcgf_model = FCGFModel(num_feats,
  File "/home/houyongkuo/Documents/DeepGlobalRegistration/model/resunet.py", line 518, in __init__
    self.conv4_tr = conv_tr(
  File "/home/houyongkuo/Documents/DeepGlobalRegistration/model/residual_block.py", line 72, in conv_tr
    return ME.MinkowskiConvolutionTranspose(
TypeError: __init__() got an unexpected keyword argument 'has_bias'

**Comment by cattaneod** [comment]
I got the same error.

I solved the 'has_bias' by replacing it with 'bias', but I'm still getting the 'feat_model' error.

**Comment by JKViswanadham14** [comment]
any updates on this?

**Comment by Feegooddddd** [comment]
same error

**Comment by gitouni** [comment]
I think the best solution is to change the branch version to 0.5.
